### ISSUE TITLE
FlowExpressionParseException is caught and the error is not reported to the user (umbrella issue)

### ISSUE THREAD

**Issue by jthaine** [typetools/checker-framework#657]
In several places in the framework and in checkers, FlowExpressionParseException are ignored, including in BaseTypeVisitor.checkPreconditions. In some cases this results in preconditions not being checked when they should be, for example. The assumption is that the error will be reported elsewhere, such as the declaration site of a variable, instead of a use of the variable. This assumption does not always hold.

Go over all instances in the framework and in checkers where a FlowExpressionParseException is caught, and for each case reconsider whether to report the error to the user.

**Comment by jthaine** [comment]
Fix the immediate issue, suppress warnings for the tests that are failing, and file separate issues for those suppressed warnings.

**Comment by jthaine** [comment]
Based on the warnings issued by Daikon and plume-lib type check (see the pull requests https://github.com/codespecs/daikon/pull/57/ and https://github.com/mernst/plume-lib/pull/16), the following issues need to be fixed before the fix for this issue is pushed:

- [ ] Issue #752 ( Flow Expression parser: add support for package names )
- [ ] Issue #764 ( Flow Expression parser: cannot parse expression referring to static field of outer class )
- [ ] Issue #767 ( Compilation order changes type checking involving preconditions )

Here are the numbers of warnings that were suppressed for these issues:

-18 warnings were suppressed in Daikon for errors due to one or both of #767 and #752.
-4 warnings were suppressed in Daikon, and 1 in plume-lib, for errors due to issue #767 alone.
-5 warnings were suppressed in Daikon for errors due to issue #752 alone.
-1 warning was suppressed in Daikon for an error due to issue #764 alone.
