### ISSUE TITLE
Missing combination for isSubtype.

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#701]
`DefaultTypeHierarchy#isSubtype(ATM, ATM)`, (which is really isSubtypeOrConvertible) is not implemented for the following combinations (subtype_supertype):
- [x] Intersection_Primitive (`long l = t`, where the type of `t` is `T extends Long`) PR #710
- [x] Typevar_Primitive (`long l = t`, where the type of `t` is `T extends Long & Cloneable`) PR #710
- [x] Union_Intersection (When checking type argument is within bounds of type parameter.) PR ##727
- [x] Union_Union (When checking method arguments type argument substitutions) PR ##727
- [x] Array_Intersection (Testcase #738) Requires new asSuper #717 (PR #781)  

~~- [ ] Intersection_Typevar~~ (testcase in framework/tests/all-systems/Issue717.java. asSuper bug see #717)
~~- [ ] Typevar_Array (See #577)~~ Combo not valid. Error happens when a type variable is not substituted correctly
